<div class="content-header">
</tbody>
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=$this->__('From Playlist')?></h3></td>
            <td class="a-right">
                <button onclick="importForm.submit()" class="scalable save" type="button"><span>Import</span></button>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <form id="import_form" name="edit_form" method="post">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <fieldset id="import-videos">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?=$this->__('Playlist ID')?> <span class="required">*</span></td>
                    <td class="input-ele"><input class="input-text required-entry" name="playlist_id" /></td>
                </tr>
            </table>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var importForm = new varienForm('import_form');
</script>